### PR TITLE
Fixup Zlib typings to match Node docs

### PR DESCRIPTION
**Pull request by neomantra**
* Zlib functions can accept Buffer or string as first argument

 * async functions take optional second argument `options`

 * make interface ZlibCallback to shorthand all the async callbacks declarations

### CODE REVIEW

**Comment by blakeembrey** [comment]
@neomantra To make the async options optional, I'd use overloads to provide the correct type signatures. In the current PR it results in a valid `fn('', cb, cb)`. For example, try this:

```ts
export function deflate(buf: Buffer | string, callback: ZlibCallback): void;
export function deflate(buf: Buffer | string, options: ZlibOptions, callback: ZlibCallback): void;
```

**Comment by neomantra** [comment]
That makes sense; I've applied your suggestion.

**Comment by blakeembrey** [comment]
LGTM 👍 /cc @louy

**Comment by louy** [comment]
@neomantra Should those changes be done for other node versions as well? and if so, do you want to do it in this PR or should we make it a separate PR?

**Comment by neomantra** [comment]
Browsing the various node Zlib docs (e.g. https://nodejs.org/docs/v0.12.0/api/zlib.html#zlib_options), it seems that the `buf: string | Buffer` support was added in 0.10 and the `options: ZlibOptions` argument was added in 0.12.

So I'll keep 0.8 as is, add the string to 0.10, 0.11, and 0.12, and add options to 0.12.  Pull request forthcoming....

**Comment by louy** [comment]
Thank you! @neomantra

**Pull request merged**
