### PR TITLE
Stricter options in tsconfig.json

### LINKED ISSUE #5: Make sure there's `noImplicitAny`
```
typings/main/ambient/node/index.d.ts(69,3): error TS7010: 'stackTraceLimit', which lacks return-type annotation, implicitly has an 'any' return type.
```

### PR DESCRIPTION
**Pull request by louy**
Fixes #5 #6.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Those 0.8 typings with implicit anys. Let me know if you need a hand adding annotations.

**Comment by louy** [comment]
I've fixed everything in 0.8. Do you know what module `punycode` is? I couldn’t find it in the docs.
https://nodejs.org/docs/v0.8.0/api/all.html

**Comment by louy** [comment]
Nevermind. 
> Punycode.js is bundled with Node.js v0.6.2+. — https://nodejs.org/api/punycode.html

**Comment by louy** [comment]
Feel free to review this one and merge it. @blakeembrey

**Comment by blakeembrey** [comment]
LGTM 👍

**Pull request merged**
